# apiVersion: tekton.dev/v1beta1
# kind: Pipeline
# metadata:
#   name: build-and-update-pipeline
# spec:
#   tasks:
#   - name: build-image
#     taskRef:
#       name: build-image-task
#   - name: update-dep-file
#     runAfter:
#       - build-image
#     taskRef:
#       name: update-dep-file-task

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: news-demo-dev-deploy
  namespace: news-demo-dev
spec:
  # params:
  #   - name: REPO
  #   - name: REVISION
  #   - name: IMAGE
  #   - name: TAG
  #   - name: NAMESPACE
  #   - name: CONFIG_REPO_URL
  #   - name: CONFIG_REPO
  #   - name: GIT_USERNAME
  #   - name: GIT_PASSWORD
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-image-task
      taskRef:
        name: build-image-task
      workspaces:
        - name: source
          workspace: shared-workspace
      # params:
      #   - name: IMAGE
      #     value: $(params.IMAGE):$(params.TAG)
      #   - name: TAG
      #     value: $(params.TAG)
    - name: update-dep-file-task
      taskRef:
        name: update-dep-file-task
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-image-task
      # params:
      #   - name: IMAGE
      #     value: $(params.IMAGE):$(params.TAG)
      #   - name: TAG
      #     value: $(params.TAG)
