apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-dep-file
spec:
  steps:
    - name: get-latest-image
      image: alpine/git
      script: |
        git clone https://github.com/SaraTullini01/hello_world_pipeline.git /workspace/source
        cd hello_world_pipeline
        latest_image=$(curl -s https://registry.hub.docker.com/v2/repositories/saratullini01/hello_world/tags/ | jq -r '.results[].name' | sort -V | tail -n 1)
        sed -i "s/image: saratullini01/hello_world:TAG/image: saratullini01/hello_world:$latest_image/g" deployment.yaml
        git commit -am "Update deployment image tag"
        git push origin master
