name: Docker Build

on:
  push:
    branches:
      - master  # Modifica in base al tuo branch di riferimento

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: saratullini01
        DOCKER_PASSWORD: 174Sara01!
      run: |
        LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/saratullini01/hello_world/tags" | jq -r '.results[0].name')
        echo "Latest Tag: $LATEST_TAG"
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t saratullini01/hello_world:$LATEST_TAG -t saratullini01/hello_world:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push saratullini01/hello_world:$LATEST_TAG
        docker push saratullini01/hello_world:latest

    - name: Update Deployment
      env:
        KUBE_CONFIG_DATA: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority: /home/sara/.minikube/ca.crt
              extensions:
              - extension:
                  last-update: Sat, 13 Jan 2024 13:50:12 CET
                  provider: minikube.sigs.k8s.io
                  version: v1.32.0
                name: cluster_info
              server: https://127.0.0.1:32769
            name: minikube
          contexts:
          - context:
              cluster: minikube
              extensions:
              - extension:
                  last-update: Sat, 13 Jan 2024 13:50:12 CET
                  provider: minikube.sigs.k8s.io
                  version: v1.32.0
                name: context_info
              namespace: default
              user: minikube
            name: minikube
          current-context: minikube
          kind: Config
          preferences: {}
          users:
          - name: minikube
            user:
              client-certificate: /home/sara/.minikube/profiles/minikube/client.crt
              client-key: /home/sara/.minikube/profiles/minikube/client.key
      run: |
        echo "$KUBE_CONFIG_DATA" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl set image deployment/hello-world-deployment helloworld=saratullini01/hello_world:$LATEST_TAG
